name: "Terraform Deployment"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    paths:
       - '*/**'
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
    working-directory: ./eks-infra
jobs:
  terraform:
    name:   ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: test
             runner: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_TOKEN: ${{ secrets.AWS_TOKEN }}
         AWS_DEFAULT_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: run multiline code to install kubectl
        run: |
           echo install kubectl
           cd /home/runner
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
           chmod +x ./kubectl
           mv ./kubectl /usr/local/bin/kubectl
           mkdir .kube
           touch /home/runner/.kube/config.cfg
           chmod -R 777 /home/runner/.kube
           kubectl version --client
           pwd
           ls -lart
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_TOKEN }}
          aws-region: eu-west-1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: |
           rm -rf .terraform
           terraform init
#     - name: updating kube config
#       run: aws eks update-kubeconfig --region eu-west-1 --name acn-eks-clstr-testing
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -var-file=${{ matrix.environment }}/terraform.tfvars -no-color
      - name: Terraform apply
        #if: github.ref == 'refs/heads/master'
        id: apply
        run: terraform apply -auto-approve -input=false -var-file=${{ matrix.environment }}/terraform.tfvars
      - name: looking for config custom
        run: |
           cd /home/runner/.kube
           ls -lart
           cat config-custom
#      - name: Terraform destroy
#       #if: github.ref == 'refs/heads/master'
#        id: destroy
#        run: terraform destroy -auto-approve -input=false -var-file=${{ matrix.environment }}/terraform.tfvars
  comment:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
